import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import NextTopLoader from 'nextjs-toploader';
import AuthWrapper from '@/auth_wrapper';
import ToastProvider from './toast-provider';
import { config } from '@fortawesome/fontawesome-svg-core';
import '@fortawesome/fontawesome-svg-core/styles.css';
config.autoAddCss = false;

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: {
        template: '%s | QR君',
        default: 'QR君',
    },
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <AuthWrapper>
            <html lang="en">
                <body className={inter.className}>
                    <ToastProvider>
                        <NextTopLoader />
                        {children}
                    </ToastProvider>
                </body>
            </html>
        </AuthWrapper>
    );
}
